version = 1

test_patterns = ["testing/**"]

exclude_patterns = [
    "typescript/**",
    "assets/**",
    "testing/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/siddhant-deepsource/elsa"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  dialect = "typescript"

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
